apiVersion: v1
kind: ReplicationController
metadata:
  name: login-rc
  namespace: ingress-nginx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - image: smlinux/pay
        name: login
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: ingress-nginx
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: login
